// app/client-svelte/src/main/svelte/pages/clinic/VisitOverview.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { forkJoin } from "rxjs";
  import { toast } from "../../controls/Toast";
  import { VisitService } from "../../services/visit.service";
  import type { Owner } from "../../types/owner.type";
  import type { Visit } from "../../types/visit.type";

  const visitService = new VisitService();

  interface Props {
    owner: Owner;
  }

  let { owner }: Props = $props();

  let allVisit: Visit[] = $state([]);
  let loading = $state(true);
  onMount(async () => {
    try {
      loading = true;
      const search = { sort: "date,desc", "pet.owner.id": owner.id! };
      forkJoin({
        allVisit: visitService.loadAllVisit(search),
      }).subscribe({
        next: (value) => {
          allVisit = value.allVisit;
        },
        error: (err) => {
          toast.push(err);
        },
      });
    } finally {
      loading = false;
    }
  });
</script>

{#if loading}
  <div class="h-screen flex justify-center items-start">
    <span class="loading loading-spinner loading-xl"></span>
  </div>
{:else}
  <div
    class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 items-center gap-1"
  >
    {#each allVisit as visit}
      <div class="card flex flex-col border rounded-md p-2">
        <div class="flex flex-row gap-1">
          <fieldset class="fieldset w-full">
            <legend class="fieldset-legend">Pet</legend>
            <input
              aria-label="Pet"
              type="text"
              class="input w-full"
              readonly
              value={visit.petItem?.text}
            />
          </fieldset>
          <fieldset class="fieldset w-48">
            <legend class="fieldset-legend">Treatment</legend>
            <input
              aria-label="Treatment"
              type="date"
              class="input w-full"
              readonly
              value={visit.date}
            />
          </fieldset>
        </div>
        <fieldset class="fieldset w-full">
          <legend class="fieldset-legend">Vet</legend>
          <input
            aria-label="Vet"
            type="text"
            class="input w-full"
            readonly
            value={visit.vetItem?.text}
          />
        </fieldset>
        <fieldset class="fieldset w-full">
          <legend class="fieldset-legend">Diagnose</legend>
          <textarea aria-label="Diagnose" class="textarea w-full" readonly
            >{visit.text}
          </textarea>
        </fieldset>
        <a class="btn" href={"/visit/" + visit.id}>Edit</a>
      </div>
    {:else}
      <span>No visits</span>
    {/each}
  </div>
{/if}

// app/client-angular/src/main/angular/pages/clinic/visit-overview/visit-overview.ts
import {
  Component,
  DestroyRef,
  OnInit,
  inject,
  input,
  signal,
} from "@angular/core";
import { RouterLink } from "@angular/router";
import { Toast } from "../../../controls/toast/toast";
import { VisitService } from "../../../services/visit.service";
import { type Owner } from "../../../types/owner.type";
import { type Visit } from "../../../types/visit.type";

@Component({
  selector: "app-visit-overview",
  imports: [RouterLink],
  templateUrl: "./visit-overview.html",
  styles: ``,
})
export class VisitOverviewComponent implements OnInit {
  private destroyRef = inject(DestroyRef);
  private toast = inject(Toast);
  private visitService = inject(VisitService);
  loading = signal(false);

  owner = input.required<Owner>();
  allVisit = signal<Visit[]>([]);

  ngOnInit() {
    this.loading.set(true);
    const search = { sort: "date,desc", "pet.owner.id": this.owner().id! };
    const subscription = this.visitService.loadAllVisit(search).subscribe({
      next: (allVisit) => {
        this.allVisit.set(allVisit);
      },
      complete: () => {
        this.loading.set(false);
      },
      error: (err) => {
        this.toast.push(err);
      },
    });
    this.destroyRef.onDestroy(() => {
      subscription.unsubscribe();
    });
  }
}
