// app/client-angular/src/main/angular/pages/home/home.ts
import {
  Component,
  DestroyRef,
  OnInit,
  computed,
  inject,
  signal,
} from "@angular/core";
import { Toast } from "../../controls/toast/toast";
import { VersionService } from "../../services/version.service";

@Component({
  selector: "app-home",
  imports: [],
  templateUrl: "./home.html",
  styles: ``,
})
export class HomeComponent implements OnInit {
  private destroyRef = inject(DestroyRef);
  private toast = inject(Toast);
  private versionService = inject(VersionService);

  apiExplorer = signal<URL>(new URL(this.versionService.apiExplorerUrl()));
  apiExplorerHref = computed<string>(
    () => this.apiExplorer() + "/index.html#uri=/api"
  );

  apiGraphiql = signal<URL>(new URL(this.versionService.apiGraphiqlUrl()));
  apiGraphiqlHref = computed<string>(
    () => this.apiGraphiql() + "?path=/api/graphql"
  );

  version = signal("-");

  ngOnInit() {
    const subscription = this.versionService.loadVersion().subscribe({
      next: (res) => {
        this.version.set(res.version);
      },
      error: (err) => this.toast.push(err),
    });
    this.destroyRef.onDestroy(() => {
      subscription.unsubscribe();
    });
  }
}

// app/client-svelte/src/main/svelte/pages/Home.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { toast } from "../components/Toast";
  import { VersionService } from "../services/version.service";

  const versionService = new VersionService();

  let apiExplorer = versionService.apiExplorerUrl();

  let apiGraphiql = versionService.apiGraphiqlUrl();

  let version = $state("-");

  onMount(async () => {
    versionService.loadVersion().subscribe({
      next: (json) => {
        version = json.version;
      },
      error: (err) => {
        toast.push(err);
      },
    });
  });
</script>

<div class="flex flex-col ml-2 mr-2 space-y-2">
  <fieldset class="p-4 border-2 space-y-2">
    <legend class="text-xs">APP-Banner</legend>
    <div class="text-2xl">
      <img src="/pets.png" alt="Pets" />
    </div>
  </fieldset>
  <fieldset class="p-4 border-2 space-y-2">
    <legend class="text-xs">APP-Version</legend>
    <div class="text-2xl">{version}</div>
  </fieldset>
  <fieldset class="p-4 border-2 space-y-2">
    <legend class="text-xs">API-Explorer</legend>
    <div class="text-2xl">
      <a
        class="underline text-blue-600 break-all"
        href="{apiExplorer}/index.html#uri=/api"
        target="_blank"
        >{apiExplorer.pathname}
      </a>
    </div>
  </fieldset>
  <fieldset class="p-4 border-2 space-y-2">
    <legend class="text-xs">API-Graphiql</legend>
    <div class="text-2xl">
      <a
        class="underline text-blue-600 break-all"
        href="{apiGraphiql}?path=/api/graphql"
        target="_blank"
        >{apiGraphiql.pathname}
      </a>
    </div>
  </fieldset>
</div>
