// app/client-angular/src/main/angular/pages/clinic/visit-lister/visit-lister.ts
import {
  Component,
  DestroyRef,
  OnInit,
  computed,
  inject,
  signal,
} from "@angular/core";
import { CommonModule } from "@angular/common";
import { HttpParams } from "@angular/common/http";
import {
  FormControl,
  FormGroup,
  ReactiveFormsModule,
  Validators,
} from "@angular/forms";
import { forkJoin } from "rxjs";
import { PetService } from "../../../services/pet.service";
import { VetService } from "../../../services/vet.service";
import { VisitService } from "../../../services/visit.service";
import { type PetItem } from "../../../types/pet.type";
import { type VetItem } from "../../../types/vet.type";
import { type Visit } from "../../../types/visit.type";

@Component({
  selector: "app-visit-lister",
  imports: [CommonModule, ReactiveFormsModule],
  templateUrl: "./visit-lister.html",
  styles: ``,
})
export class VisitListerComponent implements OnInit {
  private destroyRef = inject(DestroyRef);
  private petService = inject(PetService);
  private vetService = inject(VetService);
  private visitService = inject(VisitService);
  loading = signal(false);

  filterForm = new FormGroup({
    criteria: new FormControl("", Validators.required),
  });

  allVisit = signal<Visit[]>([]);
  afterCreateVisit(newVisit: Visit) {
    this.allVisit.update((allVisit) => {
      return [newVisit, ...allVisit];
    });
  }
  afterUpdateVisit(newVisit: Visit) {
    this.allVisit.update((allVisit) => {
      return allVisit.map((visit) =>
        visit.id === newVisit.id ? newVisit : visit
      );
    });
  }
  afterRemoveVisit(newVisit: Visit) {
    this.allVisit.update((allVisit) => {
      return allVisit.filter((visit) => visit.id !== newVisit.id);
    });
  }

  /**
   * Start swimlane if the date changes
   * in a date ordered array.
   *
   * @param _index from #each
   */
  isSwimlaneChange(index: number) {
    if (index) {
      const visit1 = this.allVisit()[index - 1];
      const visit2 = this.allVisit()[index];
      return visit1.date !== visit2.date;
    } else {
      return true;
    }
  }

  newVisit = computed<Visit>(() => {
    return {
      version: 0,
      date: "",
      text: "",
    };
  });

  allPetItem = signal<PetItem[]>([]);
  allVetItem = signal<VetItem[]>([]);
  ngOnInit() {
    this.loading.set(true);
    const params = new HttpParams().set("sort", "date,asc");
    const subscription = forkJoin({
      allPetItem: this.petService.loadAllPetItem(),
      allVetItem: this.vetService.loadAllVetItem(),
      allVisit: this.visitService.loadAllVisit(params),
    }).subscribe({
      next: (value) => {
        this.allPetItem.set(value.allPetItem);
        this.allVetItem.set(value.allVetItem);
        this.allVisit.set(value.allVisit);
      },
      complete: () => {
        this.loading.set(false);
      },
    });
    this.destroyRef.onDestroy(() => {
      subscription.unsubscribe();
    });
  }

  onFilterClicked() {
    this.loading.set(true);
    const params = new HttpParams().set("sort", "date,desc");
    const subscription = this.visitService.loadAllVisit(params).subscribe({
      next: (allVisit) => {
        this.allVisit.set(allVisit);
      },
      complete: () => {
        this.loading.set(false);
      },
    });
    this.destroyRef.onDestroy(() => {
      subscription.unsubscribe();
    });
  }

  visitId = signal<string | undefined>(undefined); // no visit selected
  onVisitClicked(visit: Visit) {
    this.visitId.set(visit.id);
  }

  visitEditorCreate = signal(false);
  onVisitEditorCreateClicked() {
    this.visitId.set(undefined); // no visit selected
    this.visitEditorCreate.set(true);
    this.visitEditorUpdate.set(false);
  }

  visitEditorUpdate = signal(false);
  onVisitEditorUpdateClicked(visit: Visit) {
    this.visitId.set(visit.id);
    this.visitEditorCreate.set(false);
    this.visitEditorUpdate.set(true);
  }

  visitFilterDisabled = computed(
    () => this.visitEditorCreate() || this.visitEditorUpdate()
  );

  visitEditorDisabled = computed(() => this.visitFilterDisabled());

  onVisitRemoveClicked(visit: Visit) {
    this.visitId.set(undefined); // no visit selected
    const hint = visit.date;
    if (!confirm("Delete visit '" + hint + "' permanently?")) return;
    this.loading.set(true);
    const subscription = this.visitService.removeVisit(visit.id!).subscribe({
      next: (visit) => {
        this.afterRemoveVisit(visit);
      },
      complete: () => {
        this.loading.set(false);
      },
    });
    this.destroyRef.onDestroy(() => {
      subscription.unsubscribe();
    });
  }
}

// app/client-svelte/src/main/svelte/pages/clinic/VisitLister.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { forkJoin } from "rxjs";
  import { toast } from "../../components/Toast";
  import { EnumService } from "../../services/enum.service";
  import { VetService } from "../../services/vet.service";
  import { VisitService } from "../../services/visit.service";
  import type { EnumItem } from "../../types/enum.type";
  import type { VetItem } from "../../types/vet.type";
  import type { Visit } from "../../types/visit.type";
  import VisitDiagnose from "./VisitDiagnose.svelte";

  const visitService = new VisitService();
  const vetService = new VetService();
  const enumService = new EnumService();

  let allVetItem: VetItem[] = $state([]);
  let allSpeciesEnum: EnumItem[] = $state([]);
  let loading = $state(true);
  onMount(async () => {
    try {
      loading = true;
      forkJoin({
        allVetItem: vetService.loadAllVetItem(),
        allSpeciesEnum: enumService.loadAllEnum("species"),
      }).subscribe({
        next: (value) => {
          allVetItem = value.allVetItem;
          allSpeciesEnum = value.allSpeciesEnum;
        },
        error: (err) => {
          toast.push(err);
        },
      });
      loadAllVisit();
    } finally {
      loading = false;
    }
  });

  let visitId = $state("");
  function onVisitClicked(_visit: Visit) {
    visitId = _visit.id!;
  }
  function onVisitRemoveClicked(_visit: Visit) {
    visitId = _visit.id!;
    removeVisit(_visit);
  }

  let visitEditorUpdate = $state(false);
  function onVisitEditorUpdateClicked(_visit: Visit) {
    visitId = _visit.id!;
    visitEditorUpdate = true;
  }

  const visitEditorDisabled = $derived(visitEditorUpdate);

  let allVisit: Visit[] = $state([]);
  function afterCreateVisit(_visit: Visit) {
    allVisit = [_visit, ...allVisit];
  }
  function afterUpdateVisit(_visit: Visit) {
    allVisit = allVisit.map((e) => (e.id === _visit.id ? _visit : e));
  }
  function afterRemoveVisit(_visit: Visit) {
    allVisit = allVisit.filter((e) => e.id !== _visit.id);
  }

  /**
   * Start swimlane if the date changes
   * in a date ordered array.
   *
   * @param _index from #each
   */
  function isSwimlaneChange(_index: number) {
    if (_index) {
      return allVisit[_index - 1].date !== allVisit[_index].date;
    } else {
      return true;
    }
  }

  /**
   * Comparator for a date ordered swimlanes.
   */
  const dateComparator = (e1: Visit, e2: Visit) =>
    e1.date.localeCompare(e2.date);

  function loadAllVisit() {
    const search = { sort: "date,desc" };
    visitService.loadAllVisit(search).subscribe({
      next: (json) => {
        allVisit = json.sort(dateComparator);
      },
      error: (err) => {
        toast.push(err);
      },
    });
  }

  function removeVisit(_visit: Visit) {
    const hint = _visit.date;
    if (!confirm("Delete visit at '" + hint + "' permanently?")) return;
    visitService.removeVisit(_visit.id!).subscribe({
      next: (json) => {
        afterRemoveVisit(json);
      },
      error: (err) => {
        toast.push(err);
      },
    });
  }
</script>

<h1>Visit</h1>

<div class="flex flex-col gap-1 ml-2 mr-2">
  {#if loading}
    <div class="h-screen flex justify-center items-start">
      <span class="loading loading-spinner loading-xl"></span>
    </div>
  {:else}
    <table class="table-fixed">
      <thead class="justify-between">
        <tr class="bg-gray-200">
          <th class="px-2 py-3 text-left w-2/6 table-cell">
            <span class="text-gray-600">Owner</span>
          </th>
          <th class="px-2 py-3 text-left w-2/6 table-cell">
            <span class="text-gray-600">Pet</span>
          </th>
          <th class="px-2 py-3 text-left w-2/6 table-cell">
            <span class="text-gray-600">Vet</span>
          </th>
          <th class="px-2 py-3 w-16"></th>
        </tr>
      </thead>
      <tbody>
        {#each allVisit as visit, i}
          {#if isSwimlaneChange(i)}
            <tr class="bg-gray-100">
              <td class="px-2 py-3" colspan="4">
                <span class="h-5 text-xl">{visit.date}</span>
              </td>
            </tr>
          {/if}
          <tr
            onclick={(e) => onVisitClicked(visit)}
            title={visit.id}
            class:border-l-2={visitId === visit.id}
          >
            <td class="px-2 py-3 text-left table-cell">
              {visit.ownerItem?.text}
            </td>
            <td class="px-2 py-3 text-left table-cell">
              {visit.petItem?.text}
            </td>
            <td class="px-2 py-3 text-left table-cell">
              {visit.vetItem?.text}
            </td>
            <td class="px-2 py-3 table-cell">
              <div
                class="grid grid-cols-1 md:grid-cols-2 items-center gap-1 w-max"
              >
                <button
                  title="Delete a visit"
                  class="btn btn-circle btn-outline"
                  onclick={() => onVisitRemoveClicked(visit)}
                  disabled={visitEditorDisabled}
                >
                  <span class="material-icons">delete</span>
                </button>
                <button
                  title="Edit visit details"
                  class="btn btn-circle btn-outline"
                  onclick={() => onVisitEditorUpdateClicked(visit)}
                  disabled={visitEditorDisabled}
                >
                  <span class="material-icons">edit</span>
                </button>
              </div>
            </td>
          </tr>
          {#if visitEditorUpdate && visitId === visit.id}
            <tr>
              <td class="border-l-4 px-4" colspan="4">
                <VisitDiagnose
                  onupdate={afterUpdateVisit}
                  bind:visible={visitEditorUpdate}
                  {allVetItem}
                  {visit}
                />
              </td>
            </tr>
          {/if}
        {:else}
          <tr>
            <td class="px-2" colspan="3">No visits</td>
          </tr>
        {/each}
      </tbody>
    </table>
  {/if}
</div>
